
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - ytdlmp3.tools
        - www.ytdlmp3.tools
      secretName: ytdlmp3.tools

  rules:
    - host: ytdlmp3.tools
      http:
          paths:
            - path: /?(.*)
              pathType: Prefix
              backend:
                serviceName: client-cluster-ip-service
                servicePort: 3000
            - path: /api/?(.*)
              pathType: Prefix
              backend:
                serviceName: server-cluster-ip-service
                servicePort: 5000
